### ISSUE TITLE
it's down because of swiggy updated their api check once

### ISSUE THREAD

**Issue by saurabh-kud** [1hiteshk/FoodOrder-like-Swiggy#1]
you can try this to get proper data
jsondata?.data?.cards[5].card?.card?.gridElements?.infoWithStyle?.restaurants

when mapping 
use .info

**Comment by 1hiteshk** [comment]
> you can try this to get proper data jsondata?.data?.cards[5].card?.card?.gridElements?.infoWithStyle?.restaurants
> 
> when mapping use .info

yeah , updated the swiggy api link , it's now updated and live please do have a look at it now

**Comment by 1hiteshk** [comment]
done its updated, they maintain their apis time to time. so we have to update it also.
